# -*- coding: utf-8 -*-
"""Deliverable4_RunModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kuoVp7p6rn9zv7Op4fiMf6dUktQXTYp8
"""

from deliverable4_deploymodel import *

#DO NOT CHANGE THIS BLOCK
#SECTOR OPTIONS
sectorOptions = ["basicMaterials", "communicationServices", "consumerCyclical", "consumerDefensive", "energy", "financialServices", "healthcare", "industrials", "realEstate", "technology", "utilities"]

###YOU CAN CHANGE THIS BLOCK
#INCOME STATEMENT ACCOUNTS
prevRevenue = 0
currRevenue = 0
cogs = 0
ebitda = 0
ebit = 0
interestExpense = 0
netIncome = 0

###YOU CAN CHANGE THIS BLOCK
#BALANCE SHEET ACCOUNTS
cash = 0
accountsReceivable = 0
inventory = 0
currAssets = 0
totalAssets = 0
accountsPayable = 0
currLiabilities = 0
totalLiabilities = 0
preferredDividends = 0
totalEquity = 0

###YOU CAN CHANGE THIS BLOCK
#CASH FLOW STATEMENT ACCOUNTS
capex = 0

###YOU CAN CHANGE THIS BLOCK
#MARKET INFORMATION
outstandingShares = 0
dividendPerShare = 0
currPrice = 0
sector = sectorOptions[0]

##DO NOT CHANGE ANYTHING BELOW THIS COMMENT
listOfVars = [prevRevenue, currRevenue, cogs, ebitda, ebit, interestExpense, netIncome, cash, accountsReceivable, 
inventory, currAssets, totalAssets, accountsPayable, currLiabilities, totalLiabilities, preferredDividends, totalEquity,
capex, outstandingShares, dividendPerShare, currPrice, sector]

print(run_model(listOfVars))